export const BOTTOM_SHEET_MIN_Y = 88; // 바텀시트가 최대로 높이 올라갔을 때의 y 값
export const BOTTOM_SHEET_MAX_Y = window.innerHeight - 200; // 바텀시트가 최소로 내려갔을 때의 y 값
export const BOTTOM_SHEET_HEIGHT = window.innerHeight + 300; // 바텀시트의 세로 길이
export const WINDOW_HEIGHT = window.innerHeight;
export const HEADER_HEIGHT = 64;
export const BANKLIST_SHEET_MIN_Y = 190;
export const BANKLIST_SHEET_MAX_Y = window.innerHeight;
export const DRAWERHEIGHT = 200;
export const BOTTOMBARHEIGHT = 74;
