export const BankLists = [
    { name: 'NH농협', url: '/png/NH.png' },
    { name: '카카오뱅크', url: '/png/KAKAO.png' },
    { name: 'KB국민', url: '/png/KB.png' },
    { name: '토스뱅크', url: '/png/Toss.png' },
    { name: '신한', url: '/png/SinHan.png' },
    { name: '우리', url: '/png/Woori.png' },
    { name: 'IBK기업', url: '/png/IBK.svg' },
    { name: '하나', url: '/png/Hana.png' },
    { name: '새마을', url: '/png/SaeMaeul.png' },
    { name: '부산', url: '/png/BNK.png' },
    { name: '대구', url: '/png/DGB.png' },
    { name: 'NH농협', url: '/png/NH.png' },
    { name: '카카오뱅크', url: '/png/KAKAO.png' },
    { name: 'KB국민', url: '/png/KB.png' },
    { name: '토스뱅크', url: '/png/Toss.png' },
    { name: '신한', url: '/png/SinHan.png' },
    { name: '우리', url: '/png/Woori.png' },
    { name: 'IBK기업', url: '/png/IBK.svg' },
    { name: '하나', url: '/png/Hana.png' },
    { name: '새마을', url: '/png/SaeMaeul.png' },
    { name: '부산', url: '/png/BNK.png' },
    { name: '대구', url: '/png/DGB.png' },
];
