export const BankLists = [
    { name: 'NH농협', url: '/svg/BankNH.svg' },
    { name: '카카오뱅크', url: '/svg/BankKakao.svg' },
    { name: 'KB국민', url: '/svg/BankKB.svg' },
    { name: '토스뱅크', url: '/svg/BankToss.svg' },
    { name: '신한', url: '/svg/BankSinhan.svg' },
    { name: '우리', url: '/svg/BankWoori.svg' },
    { name: 'IBK기업', url: '/svg/BankIBK.svg' },
    { name: '하나', url: '/svg/BankHana.svg' },
    { name: '새마을', url: '/svg/BankSaemaeul.svg' },
    { name: '부산', url: '/svg/BankBusan.svg' },
    { name: '대구', url: '/svg/BankDaegu.svg' },
    { name: '케이뱅크', url: '/svg/BankKbank.svg' },
    { name: '신협', url: '/svg/BankSinhyeop.svg' },
    { name: '우체국', url: '/svg/BankEpost.svg' },
    { name: '제주', url: '/svg/BankJeju.svg' },
    { name: '경남', url: '/svg/BankKEB.svg' },
    { name: '광주', url: '/svg/BankGwangju.svg' },
    { name: '수협', url: '/svg/BankSuhyeop.svg' },
    { name: 'SBI저축', url: '/svg/BankSBI.svg' },
    { name: 'SC제일', url: '/svg/BankSC.svg' },
    { name: '씨티', url: '/svg/BankCity.svg' },
    { name: '전북', url: '/svg/BankJeonbook.svg' },
    { name: 'KDB 산업', url: '/svg/BankKDB.svg' },
    { name: '한국투자증권', url: '/svg/BankKoreaInvestment.svg' },
    { name: '산림조합', url: '/svg/BankSanlim.svg' },
];
